[package]
name = "ai-mate"
version = "0.3.0-rc-1"
edition = "2024"

authors = ["David Valin <hola@davidvalin.com>"]
homepage = "https://github.com/DavidValin/ai-mate"
repository = "https://github.com/DavidValin/ai-mate"
description = "A simple audio ai conversation system"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
cpal = "0.15"
crossbeam-channel = "0.5"
reqwest = { version = "0.12", features = ["multipart", "blocking", "json", "native-tls-vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
urlencoding = "2"
whisper-rs = { version = "0.15.1", features = ["log_backend", "tracing_backend"] }
hound = "3"
crossterm = "0.27"
tokio = { version = "1", features = ["rt", "macros"] }
kokoro-tiny = { version = "0.2.0", git = "https://github.com/DavidValin/kokoro-tiny.git", rev = "bdf5788" }
espeak-rs = "0.1.9"
flate2 = "1"
tar = "0.4"
sha2 = "0.10"
hex = "0.4"
directories = "5"
log = "0.4"
env_logger = "0.11"

[build-dependencies]
sha2 = "0.10"
hex = "0.4"
once_cell = "1"
